config/routes.rb
Rails.application.routes.draw do
  devise_for :adopters
  devise_for :users
 
  get '/' => 'paws#path'
  get '/paws' => 'paws#index'
  get '/paws/new' => 'paws#new'
  post '/paws' => 'paws#create'
  get '/paws/:id' => 'paws#show'
  get '/paws/:id/edit' => 'paws#edit'
  patch '/paws/:id' => 'paws#update'
  delete '/paws/:id' => 'paws#delete'

 
  get '/adopters' => 'adopters#index'
  # get '/adopters/new' => 'adopters#new'
  # post '/adopters' => 'adopters#create'
  get '/adopters/:id' => 'adopters#show'
  get '/adopters/:id/edit' => 'adopters#edit'
  patch '/adopters/:id' => 'adopters#update'
  get '/adopters:id' => 'adopters#delete'

 
  get '/users' => 'users#index'
  # post 'users' => 'users#create'
  get '/users/:id' => 'users#show' 
  get '/users/:id/edit' => 'users#edit'
  patch '/users/:id' => 'users#update'

  get '/favorite_paws' => 'favorite_paws#index'
  post '/favorite_paws' => 'favorite_paws#create'
  get '/favorite_paws/:id' => 'favorite_paws#index'
  delete '/favorite_paws/:id' => 'favorite_paws#delete'

  get '/external_favorite_paws/:id' => 'external_favorite_paws#index'
  delete '/external_favorite_paws/:id' => 'external_favorite_paws#delete'
  

  get '/paws_search' => 'paws#search_form'
  post '/paws_search' => 'paws#search_results'

  namespace :api do
    namespace :v1 do
      get '/paws' => 'paws#index'
      post '/pawsphoto' => 'paws#search_image'
      get '/external_paws' => 'external_paws#index'
      post '/external_paws' => 'external_paws#create'
    end
  end
end 

app/models/paw.rb
class Paw < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  
  belongs_to :adopters
  has_many :favorite_paws
  has_many :users, through: :favorite_paws
end

app/controllers/api/v1/paws_controller.rb
class Api::V1::PawsController < Api::V1::ApiController
  def index
    render json: data
  end

  def search_image
    @image = Image.create(image_params)
    p @image.photo.path
    require 'imgur'
    client = Imgur::Client.new(ENV['IMGUR_CLIENT_ID'])
    image = Imgur::LocalImage.new(@image.photo.path, title: 'Awesome photo')
    uploaded = client.upload(image)
    data = Unirest.get("http://pets.vsapi01.com/api-search/by-url?url=#{uploaded.link}&apikey=#{ENV['PET_API']}").body
    render json: { data: data }
  end

  def image_params
    params.permit(:photo)
  end
end

app/controllers/paws_controller.rb
class PawsController < ApplicationController
  # before_action :validate!, :except => [:index, :show]

  def path
    if current_adopter 
      redirect_to '/adopters'
    elsif current_user
      redirect_to '/users'
    else
      redirect_to '/paws'
    end
  end

  def index
    @paws = Paw.all 
    render 'index.html.erb'
  end

  def show
    paw_id = params[:id]
    @paw = Paw.find_by(id: paw_id)
    render 'show.html.erb'
  end

  def new
    render 'new.html.erb'
  end

  def create
    Paw.create(
      name: params[:name], 
      gender: params[:gender], 
      description: params[:description],
      breed: params[:breed],
      weight: params[:weight],
      color: params[:color],
      age: params[:age],
      special_needs: params[:special_needs],
      energy_level: params[:energy_level],
      needs_yard: params[:needs_yard],
      kids_ok: params[:kids_ok],
      fees: params[:fees],
      location: params[:location],
      image: params[:image],
      adopter_id: current_adopter.id
    )
    flash[:success] = "Pet added!"
    redirect_to "/paws"
  end

  def edit
    paw_id = params[:id]
    @paw = Paw.find_by(id: params[:id])
    render 'edit.html.erb'
  end

  def update
    paw_id = params[:id]
    @paw = Paw.find_by(id: paw_id)
    @paw.update(
      name: params[:name], 
      gender: params[:gender], 
      description: params[:description],
      breed: params[:breed],
      weight: params[:weight],
      color: params[:color],
      age: params[:age],
      special_needs: params[:special_needs],
      energy_level: params[:energy_level],
      needs_yard: params[:needs_yard],
      kids_ok: params[:kids_ok],
      fees: params[:fees]
    )
    flash[:success] = "Pet Updated!"
    redirect_to "/paws/#{@paw.id}"
  end

  def delete
    @paw = Paw.find_by(id: params[:id])
    @paw.delete
    flash[:success] = "Pet Adopted"
    redirect_to '/adopters'
  end


  private

  def image_params
    params.permit(:photo)
  end

  def paw_params
    params.require(:paw).permit(:firstname, :description, :avatar)
  end


  # private

  # def validate!
  #   unless current_adopter
  #     flash[:warning] = "You do not have permission to edit this!"
  #     redirect_to '/users'
      
  #   end
  # end
end

app/helpers/api/v1/paws_helper.rb
module Api::V1::PawsHelper
end

app/helpers/paws_helper.rb
module PawsHelper
end

app/views/paws/_form.html.erb
<%= form_for @paw, url: paws_path, html: { multipart: true } do |form| %>


<div>
  <%= @paws.each do |paw| %>
  <%= image_tag paw.avatar.url %>
  <%= form.file_field :avatar %>
  <%= form.submit "submit" %>
</div>

<div>
  <%= form.label   %>
</div>


<% end %>
<% end %>

app/views/paws/create.html.erb
<h2>Pet Added</h2>
<%= link_to "Back to all pets", "/paws" %>

app/views/paws/edit.html.erb
<%= form_tag "/paws/#{@paw.id}", method: :patch do %>

  <section id="content-region-3" class="padding-40 page-tree-bg">
            <div class="container">
                <h3 class="page-tree-text">Update Information
                    
                </h3>
            </div>
        </section><!--page-tree end here-->
        <div class="space-70"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="my-login-form">
                         <form>
                        <h4 class="heading-mini">Update</h4><hr>
                        <div class="row">
                            <div class="col-md-6 margin-btm-20">
                                <input type="text" class="form-control" placeholder="Name">
                            </div>
                             <div class="col-md-6 margin-btm-20">
                                <input type="email" class="form-control" placeholder="Descrition">
                            </div>
                             <div class="col-md-6 margin-btm-20">
                                <input type="password" class="form-control" placeholder="Gender">
                            </div>
                             <div class="col-md-6 margin-btm-20">
                                <input type="password" class="form-control" placeholder="Color">
                            </div>
                            <div class="col-md-6 margin-btm-20">
                                <input type="password" class="form-control" placeholder="Weight">
                            </div>
                            <div class="col-md-6 margin-btm-20">
                                <input type="password" class="form-control" placeholder="Age">
                            </div>
                            <div class="col-md-6 margin-btm-20">
                                <input type="password" class="form-control" placeholder="Special Needs">
                            </div>
                            <div class="col-md-6 margin-btm-20">
                                <input type="password" class="form-control" placeholder="Energy Level">
                            </div>
                            <div class="col-md-6 margin-btm-20">
                                <input type="password" class="form-control" placeholder="Needs a Yard">
                            </div>
                            <div class="col-md-6 margin-btm-20">
                                <input type="password" class="form-control" placeholder="Kids Ok">
                            </div>
                            <div class="col-md-6 margin-btm-20">
                                <input type="password" class="form-control" placeholder="Fees">
                            </div>
                            <div class="col-md-6 margin-btm-20">
                                <input type="password" class="form-control" placeholder="Location">
                            </div>
                            <div class="col-md-12 text-right">
                                <button type="submit" class="btn theme-btn-color">Submit</button>
                            </div>

                        </div>
                        <hr>
                        <div class="form-btm-link text-center">
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
        <% end %>

app/views/paws/index.html.erb
<section id="content-region-3" class="padding-40 page-tree-bg">
    <div class="container">
        <h3 class="page-tree-text">
            Pets looking for a home
        </h3>
    </div>
</section><!--page-tree end here-->
<div class="space-70"></div>

<div class="portfolio-masonary-wrapper">
  <div class="container mas-boxes">
    <% @paws.each do |paw|%>
      <div class="mas-boxes-inner direc-hover-box wow animated fadeInUp">
          <a href="/paws/<%= paw.id %>">
              <img src="<%= paw.image %>" class="img-responsive" alt="">
              <div class="direc-overlay">
                  <span>
                    <h2>Name: <%= paw.name %></h2>
                    <p><%= paw.breed %></p>
                    <p><%= paw.description %></p>
                  </span>
              </div>
          </a>
      </div><!--masonry box-->
    <% end %>
  </div>

  <div ng-app="app">
    <div ng-controller="pawCtrl" ng-init="setup()">
      <div ng-app="myApp">
        </div>
      <div class="container">
      <div class="search">
        <h3>Or, upload a photo:</h3>
        <form>
          <input type="file" accept="image/*;capture=camera" class="btn theme-btn-default btn-lg" file-model="fileToUpload"/>
          <button class="btn theme-btn-default btn-lg" ng-click="searchPaw2(fileToUpload)">Search</button>
        </form>
      </div>
      </div>

      <div class="cat" ng-if="loadingSearch">
      <p>Loading your matches...</p>
      <style>
      .cat {
        text-align: center;
      p {
        text-align: center;
      }
      }
      </style>

        <img src="assets/img/346.gif" alt="" style="width:60px;height:60px;">
      </div>
      
      <div class="container" ng-repeat="paw in paws">
        <h2>{{ paw.petName }}</h2>
        <h2>{{ paw.petDescription }}</h2>
        <button ng-click="addToExternalFavorite(paw)"class="btn theme-btn-default btn-lg">Add to favorite</button>
        <img ng-src="{{paw.imageUrl}}">
      </div>
    </div>
  </div>

</div><!--masonary wrapper-->
<script src="/assets/js/jquery.min.js" type="text/javascript"></script>
<script src="/assets/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/assets/js/jquery-migrate.min.js" type="text/javascript"></script>
<script src="/assets/js/jquery.masonry.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/assets/js/modernizr.custom.97074.js"></script>
<script src="/assets/js/jquery.easing.1.3.min.js" type="text/javascript"></script>
<script src="/assets/js/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="/assets/js/jquery.sticky.js" type="text/javascript"></script>
<script src="/assets/js/parallax.min.js" type="text/javascript"></script>
<script src="/assets/js/jquery.flexslider-min.js" type="text/javascript"></script>
<script src="/assets/js/jquery.mixitup.min.js" type="text/javascript"></script>
<script src="/assets/js/wow.min.js" type="text/javascript"></script>
<script src="/assets/js/app.js" type="text/javascript"></script>
<script src="/assets/js/masonary-custom.js" type="text/javascript"></script>
<script src="/assets/js/modernizr.custom.97074.js" type="text/javascript"></script>
<script src="/assets/js/jquery.hoverdir.js" type="text/javascript"></script>
<script type="text/javascript">
    $(function () {

        $(' .mas-boxes > .direc-hover-box ').each(function () {
            $(this).hoverdir();
        });

    });
</script>
<div class="space-70"></div>

app/views/paws/new.html.erb
<%= form_tag '/paws', method: :post do %>
  <section id="content-region-3" class="padding-40 page-tree-bg">
            <div class="container">
                <h3 class="page-tree-text">Add a Pet</h3>
            </div>
        </section><!--page-tree end here-->
        <div class="space-70"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="my-login-form">
                         <form>
                        <h4 class="heading-mini">New Pet</h4><hr>
                        <div class="row">
                            <div class="col-md-6 margin-btm-20">
                                <input type="text" class="form-control" placeholder="Name">
                            </div>
                             <div class="col-md-6 margin-btm-20">
                                <input type="email" class="form-control" placeholder="Descrition">
                            </div>
                             <div class="col-md-6 margin-btm-20">
                                <input type="password" class="form-control" placeholder="Gender">
                            </div>
                             <div class="col-md-6 margin-btm-20">
                                <input type="password" class="form-control" placeholder="Color">
                            </div>
                            <div class="col-md-6 margin-btm-20">
                                <input type="password" class="form-control" placeholder="Weight">
                            </div>
                            <div class="col-md-6 margin-btm-20">
                                <input type="password" class="form-control" placeholder="Age">
                            </div>
                            <div class="col-md-6 margin-btm-20">
                                <input type="password" class="form-control" placeholder="Special Needs">
                            </div>
                            <div class="col-md-6 margin-btm-20">
                                <input type="password" class="form-control" placeholder="Energy Level">
                            </div>
                            <div class="col-md-6 margin-btm-20">
                                <input type="password" class="form-control" placeholder="Needs a Yard">
                            </div>
                            <div class="col-md-6 margin-btm-20">
                                <input type="password" class="form-control" placeholder="Kids Ok">
                            </div>
                            <div class="col-md-6 margin-btm-20">
                                <input type="password" class="form-control" placeholder="Fees">
                            </div>
                            <div class="col-md-6 margin-btm-20">
                                <input type="password" class="form-control" placeholder="Location">
                            </div>
                            <div class="col-md-12 text-right">
                                <button type="submit" class="btn theme-btn-color">Submit</button>
                            </div>

                        </div>
                        <hr>
                        <div class="form-btm-link text-center">
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
       
        <% end %>

app/views/paws/show.html.erb
<section id="content-region-3" class="padding-40 page-tree-bg">
            <div class="container">
                <h3 class="page-tree-text">Meet <%= @paw.name %></h3>
            </div>
        </section><!--page-tree end here-->
<div class="space-70"></div>
        <div class="container portfolio-details">
      
            <div class="row">
                <div class="col-md-8 portfolio-single-slide margin-btm-40">
                    <div>
                      <img src="<%= @paw.image %>" class="img-responsive" alt="">
          
                    </div><!--flex slider-->
                    <div class="portfolio-single-desc">
                        <h3><%= @paw.name %></h3>
                        <h4><%= @paw.description%></h4>
  
                        <hr>
                    </div><!--portfolio detail-->
                </div>
                <div class="col-md-4">
                    <div class="portfolio-side-bar">
                        <p>
                            <strong>My Name is: </strong><%= @paw.name %>
                        </p>
                          <p>
                            <strong>I am a: </strong><%= @paw.gender %>
                        </p>
                         <p>
                            <strong>Breed: </strong><%= @paw.breed %>
                        </p> 
                        <p>
                            <strong>I weigh: </strong><%= @paw.weight %>
                        </p> 
                        <p>
                            <strong>Color: </strong><%= @paw.color %>
                        </p>
                         <p>
                            <strong>I am: </strong><%= @paw.age %> years old.
                        </p> 
                        <p>
                            <strong>My energy level is : </strong><%= @paw.energy_level %> out of 5.
                        </p> 
                        <p>
                            <strong>I need a yard : </strong><%= @paw.needs_yard %>
                        </p> 
                        <p>
                            <strong>I have special needs : </strong><%= @paw.special_needs %>
                        </p> 
                        <p>
                            <strong>Kids are ok: </strong><%= @paw.kids_ok %>
                        </p>
                        <p>
                            <strong>Visit me at </strong><%= @paw.location %>
                        </p>
                        <br>
                        <p>
                            <a href="/paws" class="btn btn-radius theme-btn-color">Back to all Pets</a>
                            <%= form_tag "/favorite_paws", method: :post do %>
                              <%= hidden_field_tag :paw_id, @paw.id %>
                              <%= submit_tag "Add to favorites", class: "btn btn-success" %>
                            <% end %>

                        </p>
                    </div>
                </div>
            </div>
        </div><!--portfolio single container end-->
      
        <div class="space-70"></div>


        <script src="/assets/js/jquery.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="/assets/js/modernizr.custom.97074.js"></script>
        <script src="/assets/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="/assets/js/jquery.easing.1.3.min.js" type="text/javascript"></script>
        <script src="/assets/js/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
        <script src="/assets/js/jquery.sticky.js" type="text/javascript"></script>
        <script src="/assets/js/jquery.flexslider-min.js" type="text/javascript"></script>
        <script src="/assets/js/jquery.mixitup.min.js" type="text/javascript"></script>
        <script src="/assets/js/parallax.min.js" type="text/javascript"></script>
        <script src="/assets/js/wow.min.js" type="text/javascript"></script>
        <script src="/assets/js/app.js" type="text/javascript"></script>